//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ListSanPham_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ListSanPham_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
  
    ViewBag.Title = "ListSanPham";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
__o = Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-warning" });


#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
    foreach (var item in Model)
    {
        

#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.TenSP);


#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
                     __o = Html.DisplayFor(modelItem => item.Hinh);


#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.GiaSP);


#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.SoLuongTon);


#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.MoTa);


#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.MaLoai);


#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.DisplayFor(modelItem => item.NCC.TenNCC);


#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.ActionLink("Edit", "Edit", new { id = item.MaSP });


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.ActionLink("Detail", "Detail", new { id = item.MaSP });


#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
           __o = Html.ActionLink("Delete", "Delete", new { id = item.MaSP });


#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Areas\Admin\Views\SanPhams\ListSanPham.cshtml"
             
    }

#line default
#line hidden
}
}
}
