//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
             __o = Url.Action("ThemGioHang", "GioHang");


#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
    using (Html.BeginForm("ListSanPham", "SanPham", FormMethod.Get, new { @class = "form-inline flex items-center", @style = "margin-top: 12px;" }))
    {
        

#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                                                __o = ViewBag.Keyword;


#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
              
        

#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
            
    }

#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                        foreach (var item in Model.listLoai)
                        {                          
                            

#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                               __o = item.TenLoai;


#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                 
                        }

#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                        foreach (var item in Model.listLoai)
                        {
                            

#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                               __o = item.TenLoai;


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                 
                        }

#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                        foreach (var item in Model.listSP.Take(8))
                        {
                            

#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                                                    __o = Url.Action("Detail", "SanPham", new { id=item.MaSP });


#line default
#line hidden

#line 16 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                             __o = Html.DisplayFor(modelItem => item.Hinh);


#line default
#line hidden

#line 17 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                   __o = Html.DisplayFor(modelItem => item.TenSP);


#line default
#line hidden

#line 18 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                           __o = Html.DisplayFor(modelItem => item.GiaSP);


#line default
#line hidden

#line 19 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                                                                                                                                                                                                                                                                                  __o = item.MaSP;


#line default
#line hidden

#line 20 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\Home\Index.cshtml"
                                  
                        }

#line default
#line hidden
}
}
}
