//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 24 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
using LTW.Models;

#line default
#line hidden

public class _Page_DatHang_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_DatHang_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
  
    ViewBag.Title = "DatHang";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
__o = Html.ActionLink("Create New", "Create");


#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
       __o = Html.DisplayNameFor(model => model.TenSanPham);


#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
       __o = Html.DisplayNameFor(model => model.hinh);


#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
       __o = Html.DisplayNameFor(model => model.giaban);


#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
       __o = Html.DisplayNameFor(model => model.isoluong);


#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
       __o = Html.DisplayNameFor(model => model.dThanhtien);


#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
    foreach (var item in Model)
    {
        

#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
           __o = Html.DisplayFor(modelItem => item.MaSP);


#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
           __o = Html.DisplayFor(modelItem => item.TenSanPham);


#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                     __o = item.hinh;


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
            using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @id = item.MaSP }))
            {
                

#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
               __o = String.Format("{0:0,0}", item.giaban);


#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                                                   
                

#line default
#line hidden

#line 16 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
               __o = Html.DisplayFor(modelItem => item.isoluong);


#line default
#line hidden

#line 17 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                                                      
                

#line default
#line hidden

#line 18 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
               __o = String.Format("{0:0,0}", item.dThanhtien);


#line default
#line hidden

#line 19 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                                                       
            }

#line default
#line hidden

#line 20 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             
    }

#line default
#line hidden

#line 21 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                        __o = ViewBag.TongSoLuong;


#line default
#line hidden

#line 22 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                              __o = String.Format("{0:0,0}", ViewBag.TongTien);


#line default
#line hidden

#line 23 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                   __o = Html.ActionLink("Tr? v? gi? hàng", "Giohang", "GioHang");


#line default
#line hidden

#line 25 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
  
    KhachHang kh = (KhachHang)Session["TaiKhoan"];



#line default
#line hidden

#line 26 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
    using (Html.BeginForm())
    {
        

#line default
#line hidden

#line 27 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
   __o = Html.ValidationSummary(true);


#line default
#line hidden

#line 28 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                     
        

#line default
#line hidden

#line 29 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                    __o = kh.TenKhachHang;


#line default
#line hidden

#line 30 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             

        

#line default
#line hidden

#line 31 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                    __o = kh.Email;


#line default
#line hidden

#line 32 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             

        

#line default
#line hidden

#line 33 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                    __o = kh.DiaChi;


#line default
#line hidden

#line 34 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             

        

#line default
#line hidden

#line 35 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                    __o = kh.SDT;


#line default
#line hidden

#line 36 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             

        

#line default
#line hidden

#line 37 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
                                    __o = DateTime.Now.ToShortDateString();


#line default
#line hidden

#line 38 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             


        

#line default
#line hidden

#line 39 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             


        

#line default
#line hidden

#line 40 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
           __o = Html.DropDownList("TrangThai", new SelectList(ViewBag.TrangThai, "MaTT", "TenTT"));


#line default
#line hidden

#line 41 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             

        

#line default
#line hidden

#line 42 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\GioHang\DatHang.cshtml"
             
    }

#line default
#line hidden
}
}
}
