//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ListNhaCungCap_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ListNhaCungCap_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
  
    ViewBag.Title = "ListNhaCungCap";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
       __o = Html.DisplayFor(modelItem => item.TenNCC);


#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
       __o = Html.ActionLink("Chi Ti?t Nhà Cung C?p", "Detail", new { id=item.MaNCC });


#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\1B295748BBE8BAC1F0A311D6DBDAA25C87B5\5\LTW\Views\NhaCungCap\ListNhaCungCap.cshtml"
         
}

#line default
#line hidden
}
}
}
