//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
               __o = Html.ActionLink("SHOPGIADUNG", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Trang chủ", "Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Danh mục", "ListLoai", "Loai");


#line default
#line hidden

#line 7 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Sản phẩm", "ListSanPham", "SanPham");


#line default
#line hidden

#line 8 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("About", "About", "Home");


#line default
#line hidden

#line 9 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Contact", "Contact", "Home");


#line default
#line hidden

#line 10 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng Kí", "DangKy", "NguoiDung");


#line default
#line hidden

#line 11 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                using (Html.BeginForm("Index", "Home", FormMethod.Get, new { @class = "form-inline flex items-center" }))

                // @using (Html.BeginForm("ListSanPham", "SanPham", FormMethod.Get, new { @class = "form-inline flex items-center" }))

                {
                    

#line default
#line hidden

#line 12 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                                                                            __o = ViewBag.Keyword;


#line default
#line hidden

#line 13 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                          
                    

#line default
#line hidden

#line 14 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                        


                }

#line default
#line hidden

#line 15 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 16 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 17 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
                 __o = Url.Action("GioHangPartial", "GioHang");


#line default
#line hidden

#line 18 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 19 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 20 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden

#line 21 "C:\Users\ASUS\AppData\Local\Temp\6EE36B4C6683707C07936E2B919496F84E8A\2\LTW\Views\Shared\_Layout.cshtml"
__o = RenderSection("upload", required: false);


#line default
#line hidden
}
}
}
